global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-db1'
    metrics_path: /probe
    params:
        auth_module: [mysql]
    static_configs:
      - targets:
        - mysql:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld-exporter:9104

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'caddy'
    scheme: http
    metrics_path: /metrics/
    static_configs:
      - targets: ['caddy:8081']

  - job_name: 'nextcloud'
    scrape_interval: 90s
    static_configs:
      - targets: ['nextcloud-exporter:9205']

  - job_name: 'garage'
    authorization:
      type: Bearer
      credentials: 'v7okP3yRtbIeLiAOVD3AV5PlTaSfXRKlQg1qCg3zoAg='
    static_configs:
      - targets:
        - 'garage:3903'