metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "d9f3b29286d72168b3762c525c9d2f996bba0fca051906ac6452cb5264b05a9b"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".minio-api-m300.local"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".minio-web-m300.local"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "lZVAgzJNHMlly1A5RFwTUU+kbwF/pOx93D+wmas6/KY="
metrics_token = "v7okP3yRtbIeLiAOVD3AV5PlTaSfXRKlQg1qCg3zoAg="
