---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: your_strong_root_password_here # <<-- IMPORTANT: Change this to a strong password
---