

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_service
    environment:
      PMA_HOST: mysql_service
      PMA_PORT: "3306" # Keep as string if PMA expects it
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # Read from .env
    # ports: # Ports are now managed by Traefik
      # - "30888:80"
    networks:
      - my_app_net
    restart: unless-stopped
    depends_on: # Good practice to ensure mysql is at least attempted to start first
      mysql: # Service name from the mysql compose file
        condition: service_healthy # Wait for healthcheck
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin-m300.local`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80" # Internal port of phpmyadmin

networks:
  my_app_net:
    external: true
    name: my_app_net