version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: "12345678" #
    volumes:
      - mysql_app_data:/var/lib/mysql
    ports:
      - "3306:3306" #
    networks:
      - my_app_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3306", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

volumes:
  mysql_app_data: # This volume will be named 'app_mysql_app_data' by default

networks:
  my_app_net:
    external: true
    name: my_app_net # Must match the name in docker-compose.network.yml