

services:
  loki:
    image: grafana/loki:latest
    container_name: loki_service
    # ports: # Ports are now managed by Traefik
      # - "3100:3100"
    volumes:
      - ./loki-config:/etc/loki
      - loki_app_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - my_app_net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki-m300.local`)"
      - "traefik.http.routers.loki.entrypoints=web"
      - "traefik.http.services.loki.loadbalancer.server.port=3100" # Internal port of Loki

  minio:
    image: minio/minio:latest
    container_name: minio_service
    # ports: # Ports are now managed by Traefik
      # - "9001:9000" # API
      # - "9002:9090" # Console
    volumes:
      - minio_app_data:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"       # Read from .env
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}" # Read from .env
    command: server /data --console-address ":9090"
    networks:
      - my_app_net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # MinIO API
      - "traefik.http.routers.minio-api.rule=Host(`minio-api-m300.local`)"
      - "traefik.http.routers.minio-api.entrypoints=web"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000" # Internal API port
      # MinIO Console
      - "traefik.http.routers.minio-console.rule=Host(`minio-console-m300.local`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9090" # Internal console port

volumes:
  loki_app_data:
  minio_app_data:

networks:
  my_app_net:
    external: true
    name: my_app_net