

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # Read from .env
    volumes:
      - mysql_app_data:/var/lib/mysql
    # ports: # Ports are managed by Traefik if external access is needed; otherwise, only via internal network
      # - "3306:3306" 
    networks:
      my_app_net: # Connects to the network defined in traefik's compose file
        # No 'external: true' or 'name:' needed here if defined in the same project context
        # However, to be absolutely clear that it uses the one defined by Traefik's compose:
        # external: true # This is if Traefik's network is considered "external" to this specific file's scope
                      # For multiple compose files under one project (--project-name),
                      # simply listing the network name is usually enough if defined elsewhere.
                      # If 'traefik' service and its network are started first, this service will join it.
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3306", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    labels:
      # Traefik labels are typically NOT used for databases unless you intend to expose them directly
      # via Traefik's TCP routing, which is less common.
      - "traefik.enable=false" # Explicitly disable Traefik for this service if no web/tcp exposure needed
      # If you DID want to expose MySQL TCP port 3306 via Traefik (e.g., on traefik host port 33060):
      # - "traefik.enable=true"
      # - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)" # Or more specific if using SNI
      # - "traefik.tcp.routers.mysql.entrypoints=mysql" # Requires a custom TCP entrypoint in Traefik for port 33060
      # - "traefik.tcp.routers.mysql.service=mysql-svc"
      # - "traefik.tcp.services.mysql-svc.loadbalancer.server.port=3306" # Internal MySQL port
      # And in traefik's command: --entrypoints.mysql.address=:33060

volumes:
  mysql_app_data: # This volume will be named 'myapp_mysql_app_data'

networks: # This top-level networks key is crucial for other services
  my_app_net:
    external: true # Signifies this file expects my_app_net to be defined elsewhere (e.g., by traefik's compose file)
    name: my_app_net # Ensures it connects to the correctly named network