---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:  
    - port: 80          # Internal cluster IP port for this service
      targetPort: 80    # Port on your phpMyAdmin pod
      nodePort: 30888   # The port you want to access it on from outside the cluster node
      protocol: TCP
---